#define STURDY_00 KC_V
#define STURDY_01 KC_M 
#define STURDY_02 KC_L 
#define STURDY_03 KC_C 
#define STURDY_04 KC_P 
#define STURDY_05 KC_B 
#define STURDY_06 MAGIC 
#define STURDY_07 KC_U 
#define STURDY_08 KC_O 
#define STURDY_09 KC_QUOT 
#define STURDY_10 KC_S 
#define STURDY_11 KC_T 
#define STURDY_12 KC_R 
#define STURDY_13 LT(_NAV,KC_D)
#define STURDY_14 KC_Y 
#define STURDY_15 KC_F 
#define STURDY_16 LT(_NAV,KC_N)
#define STURDY_17 KC_E 
#define STURDY_18 KC_A 
#define STURDY_19 KC_I 
#define STURDY_20 KC_X 
#define STURDY_21 LCTL_T(KC_K)
#define STURDY_22 LALT_T(KC_J)
#define STURDY_23 LGUI_T(KC_G)
#define STURDY_24 KC_W 
#define STURDY_25 KC_Z 
#define STURDY_26 RGUI_T(MY_H)
#define STURDY_27 RALT_T(KC_COMM)
#define STURDY_28 RCTL_T(KC_DOT)
#define STURDY_29 KC_UNDS  
#define STURDY_30 OS_LSFT 
#define STURDY_31 LSFT_T(KC_SPACE) 
#define STURDY_32 KC_MEH 
#define STURDY_33 REPEAT 
#define STURDY_34 REPEAT 
#define STURDY_35 OS_LSFT


#define NAV_00 SW_APP 
#define NAV_01 KC_ESC 
#define NAV_02 TAB_L 
#define NAV_03 TAB_R 
#define NAV_04 KC_NO 
#define NAV_05 KC_NO 
#define NAV_06 KC_BSPC 
#define NAV_07 KC_UP 
#define NAV_08 KC_DEL 
#define NAV_09 KC_Q 
#define NAV_10 OS_LSFT 
#define NAV_11 OS_LCTL 
#define NAV_12 OS_LALT 
#define NAV_13 OS_LGUI 
#define NAV_14 OSM(MOD_MEH) 
#define NAV_15 FWD 
#define NAV_16 KC_LEFT 
#define NAV_17 KC_DOWN 
#define NAV_18 KC_RIGHT 
#define NAV_19 BACK 
#define NAV_20 KC_NO 
#define NAV_21 KC_NO 
#define NAV_22 KC_NO 
#define NAV_23 KC_NO 
#define NAV_24 KC_NO 
#define NAV_25 KC_NO 
#define NAV_26 KC_NO 
#define NAV_27 KC_NO 
#define NAV_28 KC_NO 
#define NAV_29 CPYPASTE 
