#pragma once

// Layers
// https://github.com/Ikcelaks/keyboard_layouts/blob/main/magic_sturdy/magic_sturdy.md
#define ALPHA_00 KC_V
#define ALPHA_01 KC_M 
#define ALPHA_02 KC_L 
#define ALPHA_03 KC_C 
#define ALPHA_04 KC_P 
#define ALPHA_05 KC_B 
#define ALPHA_06 MAGIC 
#define ALPHA_07 KC_U 
#define ALPHA_08 KC_O 
#define ALPHA_09 KC_QUOT 
#define ALPHA_10 KC_S
#define ALPHA_11 LSFT_T(KC_T)
#define ALPHA_12 LCTL_T(KC_R) 
#define ALPHA_13 LGUI_T(KC_D)
#define ALPHA_14 KC_Y 
#define ALPHA_15 KC_F 
#define ALPHA_16 LGUI_T(KC_N)
#define ALPHA_17 LCTL_T(KC_E) 
#define ALPHA_18 LSFT_T(KC_A)
#define ALPHA_19 KC_I
#define ALPHA_20 KC_X 
#define ALPHA_21 LCTL_T(KC_K)
#define ALPHA_22 LALT_T(KC_J)
#define ALPHA_23 LALT_T(KC_G)
#define ALPHA_24 KC_W 
#define ALPHA_25 KC_Z 
#define ALPHA_26 RALT_T(KC_H)
#define ALPHA_27 RALT_T(KC_COMM)
#define ALPHA_28 RCTL_T(KC_DOT)
#define ALPHA_29 KC_UNDS 

#define ALPHA_30 KC_NO
#define ALPHA_31 LT(_NAV,KC_SPACE) 
#define ALPHA_32 OS_LSFT
#define ALPHA_33 OS_LSFT
#define ALPHA_34 REPEAT
#define ALPHA_35 KC_NO


#define NAV_00 SW_APP 
#define NAV_01 KC_ESC 
#define NAV_02 TAB_L 
#define NAV_03 TAB_R 
#define NAV_04 KC_NO 
#define NAV_05 KC_NO 
#define NAV_06 KC_BSPC 
#define NAV_07 KC_UP 
#define NAV_08 KC_DEL 
#define NAV_09 KC_Q 
#define NAV_10 OS_LSFT 
#define NAV_11 OS_LCTL 
#define NAV_12 OS_LALT 
#define NAV_13 OS_LGUI 
#define NAV_14 OSM(MOD_MEH) 
#define NAV_15 FWD 
#define NAV_16 KC_LEFT 
#define NAV_17 KC_DOWN 
#define NAV_18 KC_RIGHT 
#define NAV_19 BACK 
#define NAV_20 KC_NO 
#define NAV_21 KC_NO 
#define NAV_22 KC_NO 
#define NAV_23 CPYPASTE 
#define NAV_24 ALFRED 
#define NAV_25 KC_NO 
#define NAV_26 KC_NO 
#define NAV_27 KC_NO 
#define NAV_28 KC_NO 
#define NAV_29 KC_NO 


#define NUM_00 KC_NO
#define NUM_01 KC_NO 
#define NUM_02 KC_NO 
#define NUM_03 KC_9
#define NUM_04 KC_NO 
#define NUM_05 KC_NO 
#define NUM_06 KC_0
#define NUM_07 KC_NO 
#define NUM_08 KC_NO 
#define NUM_09 KC_NO 
#define NUM_10 KC_7 
#define NUM_11 KC_5
#define NUM_12 KC_3
#define NUM_13 KC_1
#define NUM_14 KC_NO
#define NUM_15 KC_NO
#define NUM_16 KC_2
#define NUM_17 KC_4
#define NUM_18 KC_6
#define NUM_19 KC_8
#define NUM_20 KC_NO 
#define NUM_21 KC_NO 
#define NUM_22 KC_NO 
#define NUM_23 KC_9 
#define NUM_24 KC_NO 
#define NUM_25 KC_NO 
#define NUM_26 KC_0
#define NUM_27 KC_COMM 
#define NUM_28 KC_DOT 
#define NUM_29 KC_UNDS
